sampler_config: &sampler_config
  method: mix
  num_samples: 65536
  vertex_samples: 4096

tail_config: &tail_config
  copy_joint_to_tail: False # Be careful ! If tail is important, keep it False !!!
  connect_tail_to_unique_son: True

order_config: &order_config
  skeleton_path:
    vroid: ./configs/skeleton/vroid.yaml
    mixamo: ./configs/skeleton/mixamo.yaml

validate_transform_config: &validate_transform_config
  augment_config:
    augment_affine_config:
      normalize_into: [-1.0, 1.0]
  tail_config: *tail_config
  order_config: *order_config
  sampler_config: *sampler_config

predict_transform_config: *validate_transform_config